export const UI_CONFIGS = {
  FRAME_RATE: 30,
}

export const PROGRESSION_CONFIGS = {
  EXP_NEEDED_MULTIPLIER: 1,
  EXP_GAIN_MULTIPLIER: 1,
}

export const DIFICULT_CONFIGS = {
  ENEMY_HEALTH_MULTIPLIER: 1,
  ENEMY_DAMAGE_MULTIPLIER: 1,
  ENEMY_LEVEL_MULTIPLIER: 1,
}